"use client"

import { useState, useRef, useEffect } from "react"
import { Send } from "lucide-react"
import { motion, AnimatePresence } from "framer-motion"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"

interface Message {
  id: number
  text: string
  sender: "user" | "system"
}

type Theme = "amber" | "red" | "blue" | "default"

export default function ConversationalUI() {
  const [messages, setMessages] = useState<Message[]>([
    { id: 0, text: "Hello! How can I assist you today?", sender: "system" },
  ])
  const [input, setInput] = useState("")
  const [theme, setTheme] = useState<Theme>("default")
  const scrollAreaRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (scrollAreaRef.current) {
      scrollAreaRef.current.scrollTop = scrollAreaRef.current.scrollHeight
    }
  }, [messages])

  const handleSend = () => {
    if (input.trim()) {
      const newMessage: Message = { id: messages.length, text: input.trim(), sender: "user" }
      setMessages([...messages, newMessage])
      setInput("")
      
      // Generate system response based on user input
      setTimeout(() => {
        const response = generateResponse(newMessage.text);
        const systemResponse: Message = {
          id: messages.length + 1,
          text: response.text,
          sender: "system",
        }
        setMessages((prevMessages) => [...prevMessages, systemResponse])
        setTheme(response.theme)  // Set the theme after generating a response
      }, 1000)
    }
  }

  const generateResponse = (userInput: string): { text: string; theme: Theme } => {
    // Restrict responses to only three specific questions and change theme
    const lowerCaseInput = userInput.toLowerCase()

    if (/bake cookies/.test(lowerCaseInput)) {
      return {
        text: "To bake cookies, preheat your oven to 350°F (175°C), mix butter, sugar, and flour, shape into balls, and bake for 10-12 minutes!",
        theme: "amber",
      }
    } else if (/latest model of tesla/.test(lowerCaseInput)) {
      return {
        text: "The latest model of Tesla is the Tesla Model S Plaid, known for its impressive performance and cutting-edge technology.",
        theme: "red",
      }
    } else if (/how do|how does.*aeroplane|airplane/.test(lowerCaseInput)) {
      return {
        text: "Airplanes work based on the principles of aerodynamics: lift generated by the wings overcomes gravity, while thrust from the engines propels the plane forward.",
        theme: "blue",
      }
    } else {
      return {
        text: "I'm only able to answer three specific questions: How to bake cookies, what is the latest model of Tesla, and how airplanes work. Please ask one of these questions!",
        theme: "default",
      }
    }
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  // Theme classes for different themes
  const themeClasses = {
    amber: {
      background: "bg-amber-100",
      text: "text-amber-900",
    },
    red: {
      background: "bg-red-100",
      text: "text-red-900",
    },
    blue: {
      background: "bg-blue-100",
      text: "text-blue-900",
    },
    default: {
      background: "bg-background",
      text: "text-primary",
    },
  }

  return (
    <div className="flex h-screen">
      {/* Static Sidebar */}
      <div className="w-1/3 p-8 flex flex-col justify-between bg-secondary">
        <div>
          <h1 className="text-4xl font-bold text-primary mb-4">Chat Assistant</h1>
          <p className="text-muted-foreground">Your AI-powered conversation partner</p>
        </div>
        <p className="text-sm text-muted-foreground">© 2024 Chat Assistant</p>
      </div>

      {/* Chat Container with Dynamic Theme */}
      <div className={`w-2/3 flex flex-col border-l ${themeClasses[theme].background} ${themeClasses[theme].text}`}>
        <ScrollArea className="flex-grow p-4" ref={scrollAreaRef}>
          <AnimatePresence>
            {messages.map((message) => (
              <motion.div
                key={message.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.3 }}
                className={`flex ${message.sender === "user" ? "justify-end" : "justify-start"} mb-4`}
              >
                <div
                  className={`flex items-start space-x-2 ${
                    message.sender === "user" ? "flex-row-reverse space-x-reverse" : ""
                  }`}
                >
                  <Avatar className="w-8 h-8">
                    <AvatarImage
                      src={message.sender === "user" ? "/placeholder-user.jpg" : "/placeholder.svg?height=32&width=32"}
                      alt={message.sender === "user" ? "User Avatar" : "System Avatar"}
                    />
                    <AvatarFallback>{message.sender === "user" ? "U" : "S"}</AvatarFallback>
                  </Avatar>
                  <div
                    className={`p-3 rounded-lg ${
                      message.sender === "user" ? "bg-primary text-primary-foreground" : "bg-muted"
                    }`}
                  >
                    {message.text}
                  </div>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </ScrollArea>
        <div className="p-4 border-t">
          <form onSubmit={(e) => e.preventDefault()} className="flex space-x-2">
            <Input
              type="text"
              placeholder="Type your message..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyPress={handleKeyPress}
              className="flex-grow"
            />
            <Button type="submit" onClick={handleSend} className="bg-primary text-primary-foreground">
              <Send className="w-4 h-4" />
              <span className="sr-only">Send message</span>
            </Button>
          </form>
        </div>
      </div>
    </div>
  )
}
